#!/bin/sh

reference_energies=`grep "E   =" e_summary.reference`

toplevel=`git rev-parse --show-toplevel`

ln -s $toplevel/SRC/mcci $toplevel/TESTS/N2/

nice $toplevel/TESTS/N2/mcci > $toplevel/TESTS/N2/out

new_energies=`grep "E   =" e_summary`

if [ "$new_energies" != "$reference_energies" ]
then
    echo "Error: energies do not match up with reference values"
    echo "In $toplevel/TESTS/N2"
    exit 1
else
    echo "Consistency test passed in TESTS/N2, cleaning up.."
    rm $toplevel/TESTS/N2/mcci
    rm $toplevel/TESTS/N2/weight
    rm $toplevel/TESTS/N2/civ_out
    rm $toplevel/TESTS/N2/convergence
    rm $toplevel/TESTS/N2/e_summary
    rm $toplevel/TESTS/N2/out
fi

